---
date: "2016-05-05T21:48:51-07:00"
title: Who Am I? 
---

My names Brady, I'm a Statistical Science major / Computer Science minor at MSU Denver. Previously I acquired my Associates Degree of Science - Psychology from the Community College of Denver. In my academic life I keep myself busy as a member of the MSU Honors Program and am also an officer of the MSU Statistical Science club. In my personal time I dive deep into obscure retro video games and bizarre movies! 

I intend to use these skills I'm developing to pursue a career in Data Science. It is my hope that by expanding my technical knowledge I can glean more wisdom from the world we all live in. I'm most experienced in R and Python, but I do have exposure to various other tools and am excited to continue growing my skillset. This blog will serve to chronicle my time through my journey, hosting various homework assignments and projects. 

Programming Knowledge:

- Beginner
    - R
    - Python
    - Java
    - LaTex
    - Markdown
- Exposed to
    - SQL
    - R Shiny

If you need to contact me I can be reached via email at blamson@msudenver.edu.