---
title: Homework PDFs
menu:
    main:
        params:
            icon: archives
---

Below are links to all of the pdf files that I can't be bothered to get working on the site natively. These go back to my first proper math class after becoming a math major, Trigonometry! I first started using LaTex with trig and I was completely new to anything involving code. What you'll see here is my experience learning LaTex and math simultaneously, so the process should prove interesting. I can't promise consistent quality here but I had a lot of fun making these so I wanted to keep them consolidated somewhere!

### MTH 1120 - Trigonometry (Spring 2021)

[Radians and Degrees](/homework_pdf/trig/radians_part_2.pdf)

[Graphs of the Trig Functions Part I](/homework_pdf/trig/Graphs_of_the_Trig_Functions.pdf)

[Graphs of the Trig Functions Part II](/homework_pdf/trig/Graphs_of_the_Trig_Functions2.pdf)

[Trigonometric Functions](/homework_pdf/trig/The_Unit_Circle__Trig_Functions_Part_2.pdf)

[Inverse Trig Functions](/homework_pdf/trig/Inverse_Trig_Functions.pdf)

[Complicated Trig Equations and Inequalities](/homework_pdf/trig/Solving_Complicated_Trigonometric_Equations_and_Inequalities.pdf)

[Law of Sines and Cosines](/homework_pdf/trig/Law_of_Sines_and_Cosines.pdf)

[Polar Coordinates](/homework_pdf/trig/Polar_Coordinates1.pdf)

[Conics](/homework_pdf/trig/Conics.pdf)

[Applications of Sinusoids](/homework_pdf/trig/sinusoids.pdf)

[Polar Forms of Complex Numbers](/homework_pdf/trig/Polar_Form_of_Complex_Numbers.pdf)

### MTH-3210: Probability and Statistics Homework Sets (Fall 2021)
Note: Homework set 2 here was done as a jupyter notebook and I encountered a weird bug. The second half of the pdf is entirely bold and I cannot for the life of me figure out why! 

[Homework Set 2](/homework_pdf/MTH_3210/mth3210_whw2.pdf)

[Homework Set 3](/homework_pdf/MTH_3210/mth3210_whw3.pdf)

[Homework Set 4](/homework_pdf/MTH_3210/mth3210_whw4.pdf)