---
title: MTH-3210 Project 1
author: 'Brady Lamson'
date: '2021-11-27'
slug: mth-3210-project-1
categories: []
tags: []
---

<script src="{{< blogdown/postref >}}index_files/header-attrs/header-attrs.js"></script>


<div id="simple-random-sample" class="section level3">
<h3>Simple Random Sample</h3>
<div id="poet-stephen-crane" class="section level4">
<h4>Poet: Stephen Crane</h4>
</div>
<div id="source-poems-of-stephen-crane-selected-by-gerald-d.-mcdonald-1964" class="section level4">
<h4>Source: Poems of Stephen Crane (Selected by Gerald D. McDonald (1964))</h4>
<p>Population: All poems written by Stephen Crane.<br />
Note that it is likely the selected book does not contain every single poem from this poet.</p>
<p>Total number of poems: <strong>59 poems</strong> (index starting at 1, the poem number is just the page in the book)</p>
</div>
</div>
<div id="method" class="section level3">
<h3>Method:</h3>
<p>Let x be a random positive integer such that:<br />
<span class="math display">\[1\leq x \leq 59\]</span>
This selects the poem. From there, count number of lines.<br />
Let y be a random number such that:
<span class="math display">\[1 \leq y \leq n\]</span>
where n is the number of lines.</p>
<p>From here the syllables on line y are counted.</p>
<div id="generate-our-poem-list." class="section level4">
<h4>Generate our poem list.</h4>
<p>The below code was ran to generate our list of poems. It is now commented out.</p>
<pre class="r"><code>#sample.int(59, 30, replace = TRUE)</code></pre>
<p>The list generated by this code is provided below and saved.</p>
<pre class="r"><code>poem_list &lt;- c(26, 34, 53, 16, 34, 57, 12, 35, 46, 9, 43, 17, 23, 39, 3, 39, 49, 11, 56, 
               58, 20, 59, 25, 46, 41, 21, 23, 2, 20, 11)</code></pre>
<p>Now this is where things get a bit more tedious. As a physical book is being used, for each of these poems the number of lines must be found manually. The random number y will be generated one at a time due to the nature of line-counting.  </p>
<p>The first randomly selected poem will serve as an example. The number is 26, which indicates our first poem is “I explain the silvered passing” on page 26.
This poem has a total of 13 lines.</p>
<pre class="r"><code>#sample.int(13, 1)</code></pre>
<p>sample.int(13,1) gave us the number 4. Line 4 has 10 syllables. This system will be used for the remaining 29 poems.  </p>
<p>This system guarantees that all poems have equal chance of being selected instead of longer poems having a higher chance. At least, that was the intent. A bias in this system arose when it was realized that there was a single poem that took up two pages. This, of course, means that it is more likely than the rest to be selected. Another issue encountered was that some of the stanza lines were too long for the books margins and had one word on a second line. These longer stanza lines were considered a single line for the sake of the experiment. An example of this choice is provided from the first paragraph of a poem below:</p>
<ol style="list-style-type: decimal">
<li>“There were many who went in huddled<br />
procession,<br />
</li>
<li>They knew not whither;<br />
</li>
<li>But, at any rate, success or calamity<br />
</li>
<li>Would attend all in equality.”</li>
</ol>
<p>(There were many who went, Stephen Crane)</p>
<p>This is not a perfect solution as it is difficult to maintain consistency with this methodology. Care was taken to ensure consistency with the lines that were combined. Understand this may skew the average to be higher.  </p>
<p>Below is a list of the collected syllable counts and the resulting summary statistics.  </p>
<pre class="r"><code>syllable_sample_one &lt;- c(10,8,8,8,7,7,4,12,6,5,8,10,7,8,5,11,8,11,7,8,4,8,4,4,9,11,7,4,11,3)
syllable_sample_two &lt;- c(2,6,4,7,4,3,4,5,3,4,4,4,4,8,6,6,7,4,2,4,7,6,2,4,2,6,4,10,3,5)

cat(&quot;The sample standard deviation for sample one is:&quot;, round(sd(syllable_sample_one),2),
    &quot;Syllables \n \n&quot;) </code></pre>
<pre><code>## The sample standard deviation for sample one is: 2.51 Syllables 
## </code></pre>
<pre class="r"><code>cat(&quot;The sample standard deviation for sample two is:&quot;, round(sd(syllable_sample_two),2), 
    &quot;Syllables \n \n&quot;)</code></pre>
<pre><code>## The sample standard deviation for sample two is: 1.92 Syllables 
## </code></pre>
<pre class="r"><code>cat(&quot;The summary statistics for sample one are: \n&quot;)</code></pre>
<pre><code>## The summary statistics for sample one are:</code></pre>
<pre class="r"><code>summary(syllable_sample_one)</code></pre>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##   3.000   5.250   8.000   7.433   8.750  12.000</code></pre>
<pre class="r"><code>cat(&quot;\nThe summary statistics for sample two are: \n&quot;)</code></pre>
<pre><code>## 
## The summary statistics for sample two are:</code></pre>
<pre class="r"><code>summary(syllable_sample_two)</code></pre>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##   2.000   4.000   4.000   4.667   6.000  10.000</code></pre>
<pre class="r"><code>boxplot(syllable_sample_one, syllable_sample_two,
        horizontal = TRUE, 
        xlab = &quot;Line Length (Syllables)&quot;, 
        names = c(&quot;Stephen Crane&quot;, &quot;Partner Sample&quot;))</code></pre>
<p><img src="{{< blogdown/postref >}}index_files/figure-html/unnamed-chunk-4-1.png" width="672" /></p>
</div>
<div id="frequency-table" class="section level4">
<h4>Frequency Table:</h4>
<table>
<thead>
<tr class="header">
<th># Of Syllables</th>
<th>Frequency</th>
<th>Relative Frequency</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>0</td>
<td>0</td>
</tr>
<tr class="even">
<td>2</td>
<td>0</td>
<td>0</td>
</tr>
<tr class="odd">
<td>3</td>
<td>1</td>
<td><span class="math inline">\(1/30 \approx .033\)</span></td>
</tr>
<tr class="even">
<td>4</td>
<td>5</td>
<td><span class="math inline">\(5/30 \approx .167\)</span></td>
</tr>
<tr class="odd">
<td>5</td>
<td>2</td>
<td><span class="math inline">\(2/30 \approx .067\)</span></td>
</tr>
<tr class="even">
<td>6</td>
<td>1</td>
<td><span class="math inline">\(1/30 \approx .033\)</span></td>
</tr>
<tr class="odd">
<td>7</td>
<td>5</td>
<td><span class="math inline">\(5/30 \approx .167\)</span></td>
</tr>
<tr class="even">
<td>8</td>
<td>8</td>
<td><span class="math inline">\(8/30 \approx .267\)</span></td>
</tr>
<tr class="odd">
<td>9</td>
<td>1</td>
<td><span class="math inline">\(1/30 \approx .033\)</span></td>
</tr>
<tr class="even">
<td>10</td>
<td>2</td>
<td><span class="math inline">\(2/30 \approx .067\)</span></td>
</tr>
<tr class="odd">
<td>11</td>
<td>4</td>
<td><span class="math inline">\(4/30 \approx .133\)</span></td>
</tr>
<tr class="even">
<td>12</td>
<td>1</td>
<td><span class="math inline">\(1/30 \approx .033\)</span></td>
</tr>
</tbody>
</table>
<pre class="r"><code>syllable_df_one = as.data.frame(syllable_sample_one)
ggplot(data = syllable_df_one, aes(x=syllable_sample_one, y = ..count../sum(..count..))) + 
  geom_histogram(binwidth = 1, colour = &#39;black&#39;) + 
  labs(title = &quot;Relative Frequency Histogram of Stephen Crane Poem Line Lengths&quot;,
       subtitle = &quot;Poems Selected by Gerald D. McDonald (1964)&quot;) +
  scale_x_continuous(&quot;Line Length (Syllables)&quot;, breaks = 3:12, labels = 3:12) +
  scale_y_continuous(&quot;Rel. Frequency&quot;, breaks = seq(0,.4,.05)) +
  theme_grey() </code></pre>
<p><img src="{{< blogdown/postref >}}index_files/figure-html/unnamed-chunk-5-1.png" width="672" /></p>
<p>The frequency histogram for Stephen Crane does not appear to show a normal distribution. What’s noticeable is four lengths that are substantially more frequent than the rest. A normal distribution would show a more gradual decrease in frequency as values deviate away from the mean, but here that isn’t the case. It would likely be better to refer to this as a tri-modal or even a multi-modal distribution.</p>
<p>On the other hand though, it would be unwise to completely throw out the possibility that this distribution is normal. There are many distributions that <strong>are</strong> normal and look nothing like it. The analysis done here simply states that the given historgram does not appear to match what one would traditionally call normal.</p>
<pre class="r"><code>syllable_df_two = as.data.frame(syllable_sample_two)
ggplot(data = syllable_df_two, aes(x=syllable_sample_two, y = ..count../sum(..count..))) + 
  geom_histogram(binwidth = 1, colour = &#39;black&#39;) + 
  labs(title = &quot;Relative Frequency Histogram of Charles Tomlinson Poem Line Lengths&quot;) +
       # subtitle = &quot;Poems Selected by Gerald D. McDonald (1964)&quot;) +
  scale_x_continuous(&quot;Line Length (Syllables)&quot;, breaks = 2:10, labels = 2:10) +
  scale_y_continuous(&quot;Rel. Frequency&quot;, breaks = seq(0,.4,.05)) +
  theme_grey() </code></pre>
<p><img src="{{< blogdown/postref >}}index_files/figure-html/unnamed-chunk-6-1.png" width="672" /></p>
<p>Describing this distribution as normal seems largely inaccurate. Due to the disproportionate frequency of length 4 this distribution would probably best be described as either reverse j-shaped or uni-modal and right-skewed. The same considerations from the previous histogram can be made here as well. This could definitely be a normal distribution, it just does not appear to be at a simple glance.</p>
</div>
</div>
<div id="data-analysis-conclusions" class="section level3">
<h3>Data Analysis Conclusions:</h3>
<p>Building off of the observations made in the previous section, it can be stated that both distributions are very different from each other. This goes beyond shape as well. It would be one thing if that was the main difference but it can also be seen that the Stephen Crane sample line lengths are, on average, far longer than the line length found in the second sample. This can be observed from the summary statistics and box plots which also show a far greater spread in the Stephen Crane sample. The second sample has a more dense distribution of line lengths that tend to be shorter, with a third quartile below even the median of the Stephen Crane sample.</p>
</div>
<div id="confidence-interval" class="section level3">
<h3>95% Confidence Interval</h3>
<pre class="r"><code>lower_bound &lt;- mean(syllable_sample_one) - 
  qt(1-0.05 / 2,29) * 
  sd(syllable_sample_one) / sqrt(30)

upper_bound &lt;- mean(syllable_sample_one) + 
  qt(1-0.05 / 2,29) * 
  sd(syllable_sample_one) / sqrt(30)

cat(&quot;The double sided 95% confidence interval for the population mean of Stephen Crane&quot;,
      &quot;\npoem line lengths in syllables is: \n[&quot;,
    round(lower_bound,2), &quot;,&quot;, round(upper_bound,2), &quot;]&quot;)</code></pre>
<pre><code>## The double sided 95% confidence interval for the population mean of Stephen Crane 
## poem line lengths in syllables is: 
## [ 6.49 , 8.37 ]</code></pre>
<p>In other words, it is known with 95% confidence that the true mean of Stephen Crane poem line lengths is between 6.49 and 8.37 syllables long based on our given sample.</p>
</div>
<div id="hypothesis-test" class="section level3">
<h3>Hypothesis Test</h3>
<p><span class="math display">\[H_0: \mu_0 = \mu_1\]</span>
<span class="math display">\[H_A: \mu_0 \neq \mu_1\]</span>
<span class="math display">\[\alpha = .05\]</span></p>
<p>To put this into words, the null hypothesis is that both poets true average line length is the same. The alternative hypothesis would be the opposite, that they’re different. The significance level for this test will be 0.05. This hypothesis test will first be done with code created manually to show the step by step process, and then the built in t.test() function will be used.</p>
<p>First, the functions that will be used for our hypothesis test calculations are below. Functions for two sample degrees of freedom and a two sample test statistic will be used.</p>
<p>Degrees of freedom:</p>
<pre class="r"><code>two_sample_df &lt;- function(size1,size2,sd1,sd2, print = TRUE) {
  df_num &lt;- ((sd1^2 / size1) + (sd2^2 / size2))^2
  df_den &lt;- ((sd1^2 / size1)^2 / (size1-1)) + ((sd2^2 / size2)^2 / (size2-1))
  df &lt;- floor(df_num / df_den)
  
  if (print == TRUE) {print(df)}
  
  return(df)
}</code></pre>
<p>Test Statistic:</p>
<pre class="r"><code>two_sample_test_statistic &lt;- function(x_mean, y_mean, delta_null = 0, 
                                      sd1, sd2, size1, size2) {
  num &lt;- x_mean - y_mean - delta_null
  den &lt;- sqrt((sd1^2 / size1)+(sd2^2 / size2))
  return(num/den)
}</code></pre>
<p>Next, the general statistics of each sample must be calculated. The mean, sample standard deviation, and sample size will be needed from each poet.</p>
<pre class="r"><code>crane_mean &lt;- mean(syllable_sample_one)
tomlinson_mean &lt;- mean(syllable_sample_two)
crane_sd &lt;- sd(syllable_sample_one)
tomlinson_sd &lt;- sd(syllable_sample_two)
crane_n &lt;- length(syllable_sample_one)
tomlinson_m &lt;- length(syllable_sample_two)</code></pre>
<p>After these values are collected, the test statistic can be calculated and a p-value will be generated from there.</p>
<pre class="r"><code>alpha = .05
test_statistic &lt;- two_sample_test_statistic(x_mean = crane_mean, y_mean = tomlinson_mean,
                                            sd1 = crane_sd, sd2 = tomlinson_sd, 
                                            size1 = crane_n, size2 = tomlinson_m)

degrees_of_freedom &lt;- two_sample_df(size1 = crane_n, size2 = tomlinson_m,
                                    sd1 = crane_sd, sd2 = tomlinson_sd,
                                    print = FALSE)

p_value &lt;- 2*pt(test_statistic, degrees_of_freedom, lower.tail = FALSE)

cat(&quot;The test statistic is:&quot;, test_statistic, 
    &quot;\nThe degrees of freedom are:&quot;, degrees_of_freedom, 
    &quot;\nThe p-value is:&quot;, p_value)</code></pre>
<pre><code>## The test statistic is: 4.791732 
## The degrees of freedom are: 54 
## The p-value is: 1.333705e-05</code></pre>
<p>Based on the manual calculations done here, the generated p-value is less than .05 by a large margin. This would show that there is significant evidence that the two authors have a different true mean line length and that we should reject the null hypothesis.</p>
<pre class="r"><code>t.test(syllable_sample_one, syllable_sample_two, paired=FALSE, alternative = &quot;two.sided&quot;)</code></pre>
<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  syllable_sample_one and syllable_sample_two
## t = 4.7917, df = 54.209, p-value = 1.325e-05
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  1.609185 3.924149
## sample estimates:
## mean of x mean of y 
##  7.433333  4.666667</code></pre>
<p>The built in t.test() provides near identical results, with only a slight variation in the p-value. This variation reaches the same conclusion though, that the null hypothesis should be rejected.</p>
</div>
<div id="conclusions" class="section level3">
<h3>Conclusions</h3>
<p>The results of this experiment line up with the authors assumptions entering into this project. As poetry is a very diverse and expressive form of art, it comes as no surprise that one would find significant evidence that the true average syllable lengths of the two authors would be different. The results of the hypothesis test back this up with a p-value that was far smaller than the chosen significance level.</p>
<p>The confidence interval for Stephen Crane had the true average of his poems line lengths being between 6.49 and 8.37 syllables. This makes sense as Crane frequently used 4 and 11 syllable lines, but primarily stuck to lines 7 and 8 syllables long which outweigh the outer values in the sample mean. What is surprising is the relative consistency the two poets had in their respective line lengths within their samples. Stephen Crane appeared to have three to four syllable lengths they used more frequently and Charles Tomlinson seemed to have one line length that was disproportionately represented over the others. Whether this is important or not is outside of the scope of this project but it does motivate a degree of reflection. The author wonders if other poets have a similar preference in their work. In retrospect, if this preference does exist and is not simply due to random chance it could just be a large part of a poets style. Another thing to consider is that different types of poetry lean more towards shorter or longer line lengths, so it’s possible there is more analysis that could be done on poets within a specific genre of poetry.</p>
</div>
